# Hacktiv8 Phase 0: Non Graded Challenge 4

---

By [Rifky Aliffa](https://github.com/Penzragon)

Instruction:

1. Buatlah Tensor di bawah ini dengan Python:

   ![Tensor](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cbegin%7Bbmatrix%7D%20%5Cbegin%7Bbmatrix%7D23%20%26%2050%5C%5C%207%20%26%2012%20%5Cend%7Bbmatrix%7D%20%26%20%5Cbegin%7Bbmatrix%7D57%20%26%2067%5C%5C%2099%20%26%2043%20%5Cend%7Bbmatrix%7D%20%5C%5C%20%5Cbegin%7Bbmatrix%7D75%20%26%2021%5C%5C%2057%20%26%2012%20%5Cend%7Bbmatrix%7D%20%26%20%5Cbegin%7Bbmatrix%7D87%20%26%2026%5C%5C%2018%20%26%2084%20%5Cend%7Bbmatrix%7D%20%5Cend%7Bbmatrix%7D)

2. Lakukan perkalian terhadap matrix berikut:

   ![Matrix](https://latex.codecogs.com/gif.latex?%5Cinline%20A%20%3D%20%5Cbegin%7Bbmatrix%7D%2023%20%26%2050%20%26%2019%5C%5C%207%20%26%2012%20%26%20109%5C%5C%2057%20%26%2067%20%26%2098%20%5Cend%7Bbmatrix%7D%2C%20B%20%3D%20%5Cbegin%7Bbmatrix%7D7%20%5C%5C%2022%20%5C%5C%2019%20%5Cend%7Bbmatrix%7D)

3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix di bawah ini:

   ![Matrix](https://latex.codecogs.com/gif.latex?%5Cinline%20A%20%3D%20%5Cbegin%7Bbmatrix%7D%2023%20%26%2050%20%26%2019%5C%5C%207%20%26%2012%20%26%20109%5C%5C%2057%20%26%2067%20%26%2098%20%5Cend%7Bbmatrix%7D)


## Import Library

In [1]:
import numpy as np

## Answer

### 1. Buatlah Tensor di bawah ini dengan Python:

![Tensor](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cbegin%7Bbmatrix%7D%20%5Cbegin%7Bbmatrix%7D23%20%26%2050%5C%5C%207%20%26%2012%20%5Cend%7Bbmatrix%7D%20%26%20%5Cbegin%7Bbmatrix%7D57%20%26%2067%5C%5C%2099%20%26%2043%20%5Cend%7Bbmatrix%7D%20%5C%5C%20%5Cbegin%7Bbmatrix%7D75%20%26%2021%5C%5C%2057%20%26%2012%20%5Cend%7Bbmatrix%7D%20%26%20%5Cbegin%7Bbmatrix%7D87%20%26%2026%5C%5C%2018%20%26%2084%20%5Cend%7Bbmatrix%7D%20%5Cend%7Bbmatrix%7D)

In [2]:
np.array([[[23, 50], [7, 12]], 
          [[57, 67], [99, 43]],
          [[75, 21], [57, 12]],
          [[87, 26], [18, 84]]])

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

### 2. Lakukan perkalian terhadap matrix berikut:

![Matrix](https://latex.codecogs.com/gif.latex?%5Cinline%20A%20%3D%20%5Cbegin%7Bbmatrix%7D%2023%20%26%2050%20%26%2019%5C%5C%207%20%26%2012%20%26%20109%5C%5C%2057%20%26%2067%20%26%2098%20%5Cend%7Bbmatrix%7D%2C%20B%20%3D%20%5Cbegin%7Bbmatrix%7D7%20%5C%5C%2022%20%5C%5C%2019%20%5Cend%7Bbmatrix%7D)

Membuat matrix A

In [3]:
A = [[23, 50, 19], [7, 12, 109], [57, 67, 98]]
A = np.array(A)
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

Membuat vector B

In [4]:
B = [17, 22, 19]
B = np.array(B)
B

array([17, 22, 19])

Melakukan perkalian terhadap matrix A dan vector B

In [5]:
A @ B

array([1852, 2454, 4305])

Melakukan perkalian dengan ***Hadamard Product*** (Element-wise)

In [6]:
A * B

array([[ 391, 1100,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])